# Generated by Django 5.2.4 on 2025-09-22 12:04

import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='main_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ideas/main_pictures/'),
        ),
        migrations.AddField(
            model_name='idea',
            name='status',
            field=model_utils.fields.StatusField(choices=[('new', 'new'), ('in_progress', 'in_progress'), ('done', 'done'), ('archived', 'archived')], default='new', max_length=100, no_check_for_status=True),
        ),
    ]
